### ISSUE TITLE
V4.0.0 Crash (iOS)

### ISSUE THREAD

**Issue by skdev24** [idenfy/Documentation#66]
Hey,

I'm customising the identify sdk by [overriding idenfyviews module](https://github.com/idenfy/Documentation/blob/master/pages/IOSUICustomization.md#customization-by-overriding-idenfyviews-module), made few changes and created a new `idenfyviews.framework` when the idenfy version was at V3.3.0, but as seen you people have updated the idenfy to V4.0.0, now when I override with the same edited framework with V4.0.0 I get this error in Xcode

`
dyld: Symbol not found: _$s11idenfyviews25BackButtonPressedDelegateMp
  Referenced from: /private/var/containers/Bundle/Application/A3D27D8C-0184-4E23-8EAA-6B494F6DCB28/APP_NAME.app/Frameworks/iDenfySDK.framework/iDenfySDK
  Expected in: /private/var/containers/Bundle/Application/A3D27D8C-0184-4E23-8EAA-6B494F6DCB28/APP_NAME.app/Frameworks/idenfyviews.framework/idenfyviews
 in /private/var/containers/Bundle/Application/A3D27D8C-0184-4E23-8EAA-6B494F6DCB28/APP_NAME.app/Frameworks/iDenfySDK.framework/iDenfySDK
`

Maybe can you update the [Download sample link](https://github.com/idenfy/Documentation/blob/master/pages/IOSUICustomization.md#1-download-sample), will update the my edited framework code with latest changes.

Also in V3.3.0 I seen one bug, 

When the idenfy sdk launch initially, and if you quickly press on `Lets begin` button I get this error and with app crash  

Thread 1: EXC_BREAKPOINT (code=1, subcode=0x107d2201c)

`
Swift.KeyedDecodingContainer<idenfycore.PartnerInfo.(unknown context at $1076e491c).CodingKeys>(_box: Swift._KeyedDecodingContainerBox<Foundation.(unknown context at $1edb84120)._JSONKeyedDecodingContainer<idenfycore.PartnerInfo.(unknown context at $1076e491c).CodingKeys>>)
`

let me know, if you have fixed this in V4.0.0, then please provide the latest framework sample code.

Thanks.

**Comment by skdev24** [comment]
Thanks, iDenfy for quick update🎉, download the latest framework, made my changes again, it's working perfectly.

Will close this issue.
